### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by apurvadave**
hello, I added sysdig in a few places where I thought it was appropriate. Please let me know if I need to update anything! Thanks for building this "awesome" resource!

### CODE REVIEW

**Comment by dharmeshkakadia** [comment]
Thanks @apurvadave . Sysdig is not a Mesos framework right? If so, can you please remove it from the frameworks section ? Also, I think "Monitoring Mesos examples" link will help if put right next to the link to the monitoring link. What do you think ?

**Comment by apurvadave** [comment]
@dharmeshkakadia you are correct Sysdig is not a Mesos framework. It's a monitoring and troubleshooting toolset.

Yes examples would fit perfectly with the monitoring link. would you like me to make that change?

**Comment by dharmeshkakadia** [comment]
Yes.

**Comment by dharmeshkakadia** [comment]
@apurvadave Are you still working on this?

**Pull request closed without merging**
