### PR TITLE
update README to have consistent style

### PR DESCRIPTION
**Pull request by Cosaquee**
Hi! I decided to spend some time and update README.md to have consistent style. In my opinion it is easier now to read and scan. Please tell me what you think about this PR and if you will merge this when this will be done?

### CODE REVIEW

**Comment by dharmeshkakadia** [comment]
Thanks ! Looks mostly good. Travis is complaining about 2 dead links. If you can remove them, I would merge this. 

  1. [L177] 404 https://github.com/parker20121/mesos-joshua  
  2. [L387] 404 https://github.com/gavinln/mesos-jenkins

**Comment by dharmeshkakadia** [comment]
@Cosaquee Are you interested in making the above change?

**Comment by Cosaquee** [comment]
Yes! I will probably finish this today and push it.

**Comment by dharmeshkakadia** [comment]
I think you missed removing https://github.com/gavinln/mesos-jenkins  on line 388.

**Comment by Cosaquee** [comment]
@dharmeshkakadia Ready to merge, please review :)

**Comment by dharmeshkakadia** [comment]
Thanks @Cosaquee for this. It looks much better now !

**Pull request merged**
